import unittest
from agentos.checks.diff import classify

POLICY = {
    "may_edit": ["Lib*", "ThirdParty", "Meta"],
    "ask_first": ["App*", "Suite*"],
    "never": ["*.render", "_autogenerated_", "*.fs.js"],
}


class TestClassify(unittest.TestCase):
    def test_allowed_no_findings(self):
        result = classify(POLICY, ["LibClient/src/x.fs"])
        self.assertEqual(result.findings, [])
        self.assertTrue(result.ok)

    def test_never_is_error(self):
        result = classify(POLICY, ["a/_autogenerated_/b.fs"])
        self.assertFalse(result.ok)

    def test_ask_first_is_warn(self):
        result = classify(POLICY, ["AppEggShellGallery/x.fs"])
        self.assertTrue(result.ok)
        self.assertTrue(any(finding.level == "warn" for finding in result.findings))

    def test_outside_scope_is_warn(self):
        result = classify(POLICY, ["random/thing.txt"])
        self.assertTrue(result.ok)
        self.assertTrue(any("outside" in finding.message for finding in result.findings))

    def test_never_beats_may_edit(self):
        result = classify(POLICY, ["LibClient/x.render"])
        self.assertFalse(result.ok)


if __name__ == "__main__":
    unittest.main()
