import unittest
from agentos.pathmatch import matches


class TestPathMatch(unittest.TestCase):
    def test_prefix_across_dirs(self):
        self.assertTrue(matches("LibClient/src/x.fs", "Lib*"))

    def test_app_prefix(self):
        self.assertTrue(matches("AppEggShellGallery/a.fs", "App*"))

    def test_segment_match(self):
        self.assertTrue(matches("a/_autogenerated_/b.fs", "_autogenerated_"))

    def test_suffix_glob(self):
        self.assertTrue(matches("x/y.render", "*.render"))

    def test_no_match(self):
        self.assertFalse(matches("Meta/tool.fs", "App*"))


if __name__ == "__main__":
    unittest.main()
