import unittest
from agentos.checks.diff import classify

POLICY = {
    "may_edit": ["Lib*", "ThirdParty", "Meta"],
    "ask_first": ["App*", "Suite*"],
    "never": ["*.render", "_autogenerated_", "*.fs.js"],
}


def levels(result):
    return sorted((f.level, f.message) for f in result.findings)


class TestClassify(unittest.TestCase):
    def test_allowed_no_findings(self):
        r = classify(POLICY, ["LibClient/src/x.fs"])
        self.assertEqual(r.findings, [])
        self.assertTrue(r.ok)

    def test_never_is_error(self):
        r = classify(POLICY, ["a/_autogenerated_/b.fs"])
        self.assertFalse(r.ok)

    def test_ask_first_is_warn(self):
        r = classify(POLICY, ["AppEggShellGallery/x.fs"])
        self.assertTrue(r.ok)
        self.assertTrue(any(f.level == "warn" for f in r.findings))

    def test_outside_scope_is_warn(self):
        r = classify(POLICY, ["random/thing.txt"])
        self.assertTrue(r.ok)
        self.assertTrue(any("outside" in f.message for f in r.findings))

    def test_never_beats_may_edit(self):
        r = classify(POLICY, ["LibClient/x.render"])
        self.assertFalse(r.ok)


if __name__ == "__main__":
    unittest.main()
